name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image_name: controle-contas
            context: ./backend
            dockerfile: ./backend/Dockerfile
          - image_name: controle-contas-frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile

    permissions:
      contents: read
      packages: write

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e publicar imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
